# app/config/config.yml (or config/packages/knp_snappy.yaml if using Symfony4 and the Flex recipe)
knp_snappy:
  pdf:
    enabled:    true
    binary:     /usr/local/bin/wkhtmltopdf  --viewport-size 1024x768
    options:
        - { name: 'viewport-size', value: ‘1024x768’ }
        - { name: 'page-size', value: 'A4' }
  image:
    enabled:    true
    binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
    options:    []